[features]
seeds = true
skip-lint = false

[programs.devnet]
solana_nft_staking = "EFe4sykZs9eBzrGdxhNDLAGPTk4cqfza77i66HvPPnpc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kevin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
