[features]
seeds = true
skip-lint = false

[programs.devnet]
solana_nft_staking = "AtJSvANyefwd1kCxjGngbHgyyt9K2AL9egpHifhbQh3u"
lootbox_program = "DR9bKxkN4A8AoCQfcBQ3Vz7mf8ireZ6JqWxSDfgmD72H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kevin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
